"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_1)\
[󰀵](bg:color_1 fg:color_fg)\
$username\
$localip\
[](bg:color_2 fg:color_1)\
$directory\
[](fg:color_2 bg:color_3)\
$git_branch\
$git_status\
[](fg:color_3 bg:color_4)\
$rust\
$golang\
$nodejs\
$haskell\
$python\
[](fg:color_4 bg:color_5)\
$aws\
$docker_context\
$conda\
[](fg:color_5 bg:color_6)\
$time\
[ ](fg:color_6)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg = '#fbf1c7'
color_ok = '#98971a'
color_ng = '#cc241d'
color_1 = '#2a83a2'
color_2 = '#00a3af'
color_3 = '#38b48b'
color_4 = '#d79921'
color_5 = '#665c54'
color_6 = '#3c3836'

[username]
show_always = true
style_user = "bg:color_1 fg:color_fg"
style_root = "bg:color_1 fg:color_fg"
format = '[ $user ]($style)'

[localip]
style = "bg:color_1 fg:color_fg"
format = '[󰩠 $localipv4]($style)'
ssh_only = false
disabled = false

[directory]
style = "fg:color_fg bg:color_2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol $branch ](fg:color_fg bg:color_3)]($style)'

[git_status]
style = "bg:color_3"
format = '[[($all_status$ahead_behind )](fg:color_fg bg:color_3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_4)]($style)'

[rust]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_4)]($style)'

[golang]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_4)]($style)'

[haskell]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_4)]($style)'

[python]
symbol = ""
style = "bg:color_4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_4)]($style)'

[aws]
symbol = '🅰 '
style = "bg:color_5"
format = '[$symbol($profile)(\($region\) )]($style)'

[docker_context]
symbol = ""
style = "bg:color_5"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_5)]($style)'

[conda]
style = "bg:color_5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_5)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_6"
format = '[[  $time ](fg:color_fg bg:color_6)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_ok)'
error_symbol = '[](bold fg:color_ng)'
vimcmd_symbol = '[](bold fg:color_ok)'
